# =============================================================================
# SENSORS - Home Assistant State Synchronization
# =============================================================================
# This file creates sensors that monitor Home Assistant entities and update
# the touchscreen buttons to reflect the current state of your smart devices.
#
# WHY THIS FILE EXISTS:
# When you press a button on the touchscreen, it sends a command to Home
# Assistant. But what if someone turns on a light using their phone, or a
# scene activates automatically? This file ensures the touchscreen display
# always shows the ACTUAL state of each device, not just what was last pressed.
#
# HOW IT WORKS:
# 1. Each sensor subscribes to a Home Assistant entity (switch, sensor, etc.)
# 2. When that entity's state changes, the "on_state" or "on_value" trigger fires
# 3. The trigger updates the corresponding button in lvgl.yaml to show the new state
#
# KEY CONCEPTS:
# - "platform: homeassistant" = reads state directly from Home Assistant
# - "platform: template" = calculates a value using code (lambda)
# - "entity_id:" = the Home Assistant device/entity to monitor
# - "id:" = unique name to reference this sensor elsewhere in ESPHome
# - "trigger_on_initial_state: true" = update button immediately when device boots
# - "lvgl.widget.update" = changes how a button looks on screen
# - "checked: !lambda return x;" = x is the sensor's boolean state (true/false)
#
# RELATIONSHIP TO lvgl.yaml:
# Each sensor here has a matching button in lvgl.yaml:
#   - This file READS state from Home Assistant → updates button appearance
#   - lvgl.yaml SENDS commands to Home Assistant → when button is pressed
# =============================================================================


# =============================================================================
# REGULAR SENSORS (Numeric Values)
# =============================================================================
# These sensors read numeric values like temperature and position.
# They're used to display information or calculate other states.
# =============================================================================

sensor:

  # ===========================================================================
  # SENSOR: Office Temperature (Indoor)
  # ===========================================================================
  # WHAT IT MONITORS:
  #   The temperature inside the office from sensor.office_temperature
  #   (This could be from a smart thermostat, dedicated sensor, etc.)
  #
  # WHAT IT UPDATES:
  #   The "temperatures" label in the top-left corner of the screen
  #   Format: "outdoor° / indoor°" (e.g., "15° / 22°")
  #
  # HOW IT WORKS:
  #   When the office temperature changes in Home Assistant, this sensor
  #   receives the new value and updates the label text. It combines the
  #   outdoor temperature (from the other sensor below) with this value.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → temperatures label (id: temperatures)
  # ===========================================================================
  - platform: homeassistant
    entity_id: sensor.gv_t_h_living_room_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(outdoor_temperature).state)', '(int)round(x)' ]

  # ===========================================================================
  # SENSOR: Outdoor Temperature
  # ===========================================================================
  # WHAT IT MONITORS:
  #   The temperature outside from sensor.outdoor_temperature
  #   (This could be from a weather service, outdoor sensor, etc.)
  #
  # WHAT IT UPDATES:
  #   The "temperatures" label in the top-left corner of the screen
  #   Format: "outdoor° / indoor°" (e.g., "15° / 22°")
  #
  # HOW IT WORKS:
  #   When the outdoor temperature changes in Home Assistant, this sensor
  #   receives the new value and updates the label text. It combines this
  #   value with the office temperature (from the sensor above).
  #
  # NOTE: Both temperature sensors update the same label. Either one changing
  #       will refresh the display with both current values.
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → temperatures label (id: temperatures)
  # ===========================================================================
  - platform: homeassistant
    entity_id: sensor.feerothsidney_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(office_temperature).state)' ]

# =============================================================================
# TEXT SENSORS (String Values)
# =============================================================================

text_sensor:

# =============================================================================
# BINARY SENSORS (On/Off States)
# =============================================================================
# These sensors track on/off states and update button appearances.
# When the sensor is ON (true), the button shows as "checked" (highlighted).
# When the sensor is OFF (false), the button shows as unchecked (dimmed).
# =============================================================================

binary_sensor:

  # ===========================================================================
  # SENSOR: Office Features Scene Active
  # ===========================================================================
  # WHAT IT MONITORS:
  #   Whether the "Features" (LED accent) lighting scene is currently active
  #   Watches: switch.office_features_stateful_scene in Home Assistant
  #
  # WHAT IT UPDATES:
  #   The "Features" button's visual state (highlighted when active)
  #
  # RELATED UI ELEMENT:
  #   lvgl.yaml → office_scene_features_button
  # ===========================================================================
  - platform: homeassistant
    id: light_living_room_sensor
    entity_id: light.living_room_lights_all
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: light_living_room_button
          state:
            checked: !lambda return x;
